# This file was generated by GoReleaser. DO NOT EDIT.
cask "elastic-fruit-runner" do
  name "elastic-fruit-runner"
  desc "Elastic GitHub Actions self-hosted runner manager for Apple Silicon"
  homepage "https://github.com/boring-design/elastic-fruit-runner"
  version "0.1.2-rc.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "elastic-fruit-runner"

  on_macos do
    on_intel do
      url "https://github.com/boring-design/elastic-fruit-runner/releases/download/v#{version}/elastic-fruit-runner_#{version}_darwin_amd64.tar.gz"
      sha256 "e5abe145abb70d5923a2ff41ff3e990b2c36d2c738753738580bedc01ddc604d"
    end
    on_arm do
      url "https://github.com/boring-design/elastic-fruit-runner/releases/download/v#{version}/elastic-fruit-runner_#{version}_darwin_arm64.tar.gz"
      sha256 "bbe8022308f4055eb8b266b9843bf4267260d33b28ff14679d88be7326f97102"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/boring-design/elastic-fruit-runner/releases/download/v#{version}/elastic-fruit-runner_#{version}_linux_amd64.tar.gz"
      sha256 "58a2c477f96dc746df2da6e3a51e51adde4d385c3baf3b62bf148008eee1c6f0"
    end
    on_arm do
      url "https://github.com/boring-design/elastic-fruit-runner/releases/download/v#{version}/elastic-fruit-runner_#{version}_linux_arm64.tar.gz"
      sha256 "470922190fc2c2dde3cdf66db61eaefc6b8c462c5f8214fcaaded197683fac82"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/elastic-fruit-runner"]
    end
  end

  # No zap stanza required
end
