# This file was generated by GoReleaser. DO NOT EDIT.
cask "elastic-fruit-runner" do
  name "elastic-fruit-runner"
  desc "Elastic GitHub Actions self-hosted runner manager for Apple Silicon"
  homepage "https://github.com/boring-design/elastic-fruit-runner"
  version "0.1.2-rc.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "elastic-fruit-runner"

  on_macos do
    on_intel do
      url "https://github.com/boring-design/elastic-fruit-runner/releases/download/v#{version}/elastic-fruit-runner_#{version}_darwin_amd64.tar.gz"
      sha256 "1583110a835a7ee4cd8fad5c1d635041e4ba1aecab7ab399227d3281d3232fef"
    end
    on_arm do
      url "https://github.com/boring-design/elastic-fruit-runner/releases/download/v#{version}/elastic-fruit-runner_#{version}_darwin_arm64.tar.gz"
      sha256 "1ed60c203099a9743cc748fa96016937c4d2988f4a8a9f201378b6dad5bf1dc6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/boring-design/elastic-fruit-runner/releases/download/v#{version}/elastic-fruit-runner_#{version}_linux_amd64.tar.gz"
      sha256 "08a1a4b98a631af0cfd02c1c50b4d10a5eb287b6d6fd1d73483fc6a369b45031"
    end
    on_arm do
      url "https://github.com/boring-design/elastic-fruit-runner/releases/download/v#{version}/elastic-fruit-runner_#{version}_linux_arm64.tar.gz"
      sha256 "55ddcbdd80bff9628b0d72ad8218b9575a918c9d8492f4492c104fb9a2d7f763"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/elastic-fruit-runner"]
    end
  end

  # No zap stanza required
end
