# This file was generated by GoReleaser. DO NOT EDIT.
cask "elastic-fruit-runner" do
  name "elastic-fruit-runner"
  desc "Elastic GitHub Actions self-hosted runner manager for Apple Silicon"
  homepage "https://github.com/boring-design/elastic-fruit-runner"
  version "0.1.2-rc.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "elastic-fruit-runner"

  on_macos do
    on_intel do
      url "https://github.com/boring-design/elastic-fruit-runner/releases/download/v#{version}/elastic-fruit-runner_#{version}_darwin_amd64.tar.gz"
      sha256 "af594dccc14df81590b4d181505e2096dcf6f0667a7af14f591ff0ff9749e044"
    end
    on_arm do
      url "https://github.com/boring-design/elastic-fruit-runner/releases/download/v#{version}/elastic-fruit-runner_#{version}_darwin_arm64.tar.gz"
      sha256 "d5e97d7db7f95828fa56118a1f452d89da6fb31f7394a50cdda9222ff8d10076"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/boring-design/elastic-fruit-runner/releases/download/v#{version}/elastic-fruit-runner_#{version}_linux_amd64.tar.gz"
      sha256 "3887e97f8b3c3d597ab14674f1a28b8dad32870750c61542ae216eca1bb6af0e"
    end
    on_arm do
      url "https://github.com/boring-design/elastic-fruit-runner/releases/download/v#{version}/elastic-fruit-runner_#{version}_linux_arm64.tar.gz"
      sha256 "219ae0e17a22ec17e44563973ec1ce870ebc4b5eb3cb46d9fa63d24654fad612"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/elastic-fruit-runner"]
    end
  end

  # No zap stanza required
end
