# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ElasticFruitRunner < Formula
  desc "Elastic GitHub Actions self-hosted runner manager for Apple Silicon"
  homepage "https://github.com/boring-design/elastic-fruit-runner"
  version "0.1.2-rc.6"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/boring-design/elastic-fruit-runner/releases/download/v0.1.2-rc.6/elastic-fruit-runner_0.1.2-rc.6_darwin_amd64.tar.gz"
      sha256 "732088559a7239a81e6bd92bd6aaaa733096ac4d0511272497b3a2e4b50a7ce2"

      define_method(:install) do
        bin.install "elastic-fruit-runner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/boring-design/elastic-fruit-runner/releases/download/v0.1.2-rc.6/elastic-fruit-runner_0.1.2-rc.6_darwin_arm64.tar.gz"
      sha256 "78f0142d09e2adcef920439a5285bfbebe25c2fbd85727371ba78dbf1b1cd085"

      define_method(:install) do
        bin.install "elastic-fruit-runner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/boring-design/elastic-fruit-runner/releases/download/v0.1.2-rc.6/elastic-fruit-runner_0.1.2-rc.6_linux_amd64.tar.gz"
      sha256 "80efa5ace0e654c0f333eb12ad3f3dc94d5db1dd3516e388d035ae27f1089ebc"
      define_method(:install) do
        bin.install "elastic-fruit-runner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/boring-design/elastic-fruit-runner/releases/download/v0.1.2-rc.6/elastic-fruit-runner_0.1.2-rc.6_linux_arm64.tar.gz"
      sha256 "0b84fc8406100c04d3d8762459d4d718e6ec88ba7284f0639feb7fdcdd4b397f"
      define_method(:install) do
        bin.install "elastic-fruit-runner"
      end
    end
  end

  def post_install
    (var/"elastic-fruit-runner").mkpath
  end

  def caveats
    <<~EOS
      Before starting the service, create a config file:

        mkdir -p ~/.elastic-fruit-runner
        cat > ~/.elastic-fruit-runner/env << 'EOF'
        GITHUB_TOKEN=ghp_xxx
        GITHUB_CONFIG_URL=https://github.com/your-org
        EOF

      Then start (and auto-start on login):

        brew services start elastic-fruit-runner

      View logs:

        tail -f #{var}/log/elastic-fruit-runner.log
    EOS
  end

  service do
    run [opt_bin/"elastic-fruit-runner"]
    keep_alive true
    working_dir var/"elastic-fruit-runner"
    log_path var/"log/elastic-fruit-runner.log"
    error_log_path var/"log/elastic-fruit-runner.log"
    environment_variables PATH: std_service_path_env
  end
end
