# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ElasticFruitRunner < Formula
  desc "Elastic GitHub Actions self-hosted runner manager for Apple Silicon"
  homepage "https://github.com/boring-design/elastic-fruit-runner"
  version "0.2.0"
  license "AGPL-3.0"

  depends_on "cirruslabs/cli/tart"
  depends_on "sshpass"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/boring-design/elastic-fruit-runner/releases/download/v0.2.0/elastic-fruit-runner_0.2.0_darwin_amd64.tar.gz"
      sha256 "0cd96723c27286a3fb34bfbe2811a05d4536f95314224b1ab2cdf7bbaa28a415"

      define_method(:install) do
        bin.install "elastic-fruit-runner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/boring-design/elastic-fruit-runner/releases/download/v0.2.0/elastic-fruit-runner_0.2.0_darwin_arm64.tar.gz"
      sha256 "c8591ff0bd130a300ec922ec6f56b1396e8f8a856418c319c7310501753938d8"

      define_method(:install) do
        bin.install "elastic-fruit-runner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/boring-design/elastic-fruit-runner/releases/download/v0.2.0/elastic-fruit-runner_0.2.0_linux_amd64.tar.gz"
      sha256 "389c7f0a91fd8551169dc09a16c4a3c8b1a358fae95a0cd98cd82d2052d36b51"
      define_method(:install) do
        bin.install "elastic-fruit-runner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/boring-design/elastic-fruit-runner/releases/download/v0.2.0/elastic-fruit-runner_0.2.0_linux_arm64.tar.gz"
      sha256 "ccd0e5a3b0c81de12adc41ea9ffedf1ed235aeb73f0ecbe2352ec5ae96433e27"
      define_method(:install) do
        bin.install "elastic-fruit-runner"
      end
    end
  end

  def post_install
    (var/"elastic-fruit-runner").mkpath
  end

  def caveats
    <<~EOS
      For the Docker backend, install a Docker-compatible runtime separately
      (e.g. Docker Desktop, OrbStack, Colima).

      Before starting the service, create a config file:

        mkdir -p ~/.elastic-fruit-runner
        cat > ~/.elastic-fruit-runner/env << 'EOF'
        GITHUB_TOKEN=ghp_xxx
        GITHUB_CONFIG_URL=https://github.com/your-org
        EOF

      Then start (and auto-start on login):

        brew services start elastic-fruit-runner

      View logs:

        tail -f #{var}/log/elastic-fruit-runner.log
    EOS
  end

  service do
    run [opt_bin/"elastic-fruit-runner"]
    keep_alive true
    working_dir var/"elastic-fruit-runner"
    log_path var/"log/elastic-fruit-runner.log"
    error_log_path var/"log/elastic-fruit-runner.log"
    environment_variables PATH: std_service_path_env
  end
end
