# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ElasticFruitRunner < Formula
  desc "Elastic GitHub Actions self-hosted runner manager for Apple Silicon"
  homepage "https://github.com/boring-design/elastic-fruit-runner"
  version "0.1.2-rc.18"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/boring-design/elastic-fruit-runner/releases/download/v0.1.2-rc.18/elastic-fruit-runner_0.1.2-rc.18_darwin_amd64.tar.gz"
      sha256 "f81be056be0fecdb8a71ab3b8531ad8345f6b962d89c9ea61ea6f05374a0cdaf"

      define_method(:install) do
        bin.install "elastic-fruit-runner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/boring-design/elastic-fruit-runner/releases/download/v0.1.2-rc.18/elastic-fruit-runner_0.1.2-rc.18_darwin_arm64.tar.gz"
      sha256 "7d40228f8cc1b8f5c71cb9716b8af6314cd34f5985b9aa4ca5dc9e17dba25337"

      define_method(:install) do
        bin.install "elastic-fruit-runner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/boring-design/elastic-fruit-runner/releases/download/v0.1.2-rc.18/elastic-fruit-runner_0.1.2-rc.18_linux_amd64.tar.gz"
      sha256 "9576a0331953c28c078190525f3a25524a7467068e1c1aee48d1189144be03ea"
      define_method(:install) do
        bin.install "elastic-fruit-runner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/boring-design/elastic-fruit-runner/releases/download/v0.1.2-rc.18/elastic-fruit-runner_0.1.2-rc.18_linux_arm64.tar.gz"
      sha256 "f16a37fe31ce426b48b5d63de25ff232e2721794e8743e41032aec552277c9c2"
      define_method(:install) do
        bin.install "elastic-fruit-runner"
      end
    end
  end

  def post_install
    (var/"elastic-fruit-runner").mkpath
  end

  def caveats
    <<~EOS
      Before starting the service, create a config file:

        mkdir -p ~/.elastic-fruit-runner
        cat > ~/.elastic-fruit-runner/env << 'EOF'
        GITHUB_TOKEN=ghp_xxx
        GITHUB_CONFIG_URL=https://github.com/your-org
        EOF

      Then start (and auto-start on login):

        brew services start elastic-fruit-runner

      View logs:

        tail -f #{var}/log/elastic-fruit-runner.log
    EOS
  end

  service do
    run [opt_bin/"elastic-fruit-runner"]
    keep_alive true
    working_dir var/"elastic-fruit-runner"
    log_path var/"log/elastic-fruit-runner.log"
    error_log_path var/"log/elastic-fruit-runner.log"
    environment_variables PATH: std_service_path_env
  end
end
